### PR TITLE
Set missing gettext textdomains to this plugin's name, plus hungarian translation

### PR DESCRIPTION
**Pull request by lukacspeter**
Set missing gettext textdomains to this plugin's name, plus hungarian translation. Tested in 9.5.1 👍

### CODE REVIEW

**Comment by jackburton79** [comment]
Hi!
Sorry, I totally missed this PR.
Will try to merge it tomorrow.
Thank you and sorry again.

**Comment by jackburton79** [comment]
Just for clarification (since I don't know much about gettext): why is this change needed ?

**Comment by lukacspeter** [comment]
Basically you cant translate a plugin without it.

"All translations functions take a $domain as argument; it defaults to glpi and must be changed when you are working on a plugin." from [https://glpi-developer-documentation.readthedocs.io/en/master/devapi/translations.html](url)

**Comment by jackburton79** [comment]
> Basically you cant translate a plugin without it.
> 
> "All translations functions take a $domain as argument; it defaults to glpi and must be changed when you are working on a plugin." from [https://glpi-developer-documentation.readthedocs.io/en/master/devapi/translations.html](url)

ok, makes sense

**Pull request merged**
